---
- name: Configure nfs storage
  hosts: HQ-SRV
  become: no
  tasks:
    - name: Download nfs and raid packeges
      command: apt-get install -y mdadm nfs-server

    - name: Create raid 5 array
      command: >
       mdadm --create --verbose
       /dev/md0 --level=5
       --raid-devices=3
       /dev/sdb /dev/sdc /dev/sdd
      ignore_arrors: yes

    - name: Create configure file mdadm
      command: mdadm --detail --scan > /etc/mdadm.conf

    - name: Create configure file mdadm
      filesystem:
        fstype: ext4
        dev: /dev/md0

    - name: Create mount point
      file:
        path: /raid5
        state: directory

    - name: Mount Raid array
      mount:
        path: /raid5
        src: /dev/md0
        fstype: ext4
        state: mounted

    - name: Configure autorecord mount in fstab
      lineinfile:
        path: /etc/fstab
        line: '/dev/md0 /raid5 ext4 defaults 0 0'
        state: present

    - name: Configure nfs
      file:
        path: /raid5/nfs
        state: directory

    - name: Export directory nfs
      blockinfile:
        path: /etc/exports
        block: |
          /raid5/nfs
          *(rw,sync,no_subtree_check)

    - name: Restart service nfs
      service:
        name: nfs-server
        state: restarted

    - name: Configure autorecord nfs in HQ-CLI
      hosts: HQ-CLI
      become: no
      tasks:
        - name: Download depends for nfs
          command: apt-get install -y nfs-common

        - name: Create mount point
          file:
            path: /mnt/nfs
            state: directory

        - name: Configure autorecord mounting in fstab
          linefile:
            path: /etc/fstab
            line: '192.168.100.10:/raid5/nfs /mnt/nfs nfs defaults 0 0'
            state: present

        - name: Mounting NFS
          mount:
            path: /mnt/nfs
            src: "192.168.100.10:/raid5/nfs"
            fstype: nfs
            state: mounted
